config/routes.rb
Rails.application.routes.draw do
  resources :tweeterclones do
    collection do
      post :confirm
    end
  end
  root 'tweeterclones#index'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    paginates_per 50
  self.abstract_class = true
end

app/models/tweeterclone.rb
class Tweeterclone < ApplicationRecord
    validates :content,presence:true,length:{maximum:140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweeterclones_controller.rb
class TweeterclonesController < ApplicationController
  before_action :set_tweeterclone, only: [:show, :edit, :update, :destroy]

  # GET /tweeterclones
  # GET /tweeterclones.json
  def index
    @tweeterclones = Tweeterclone.all.page params[:page]
    @tweetercount = Tweeterclone.all.count
  end

  # GET /tweeterclones/1
  # GET /tweeterclones/1.json
  def show
  end

  def confirm
    @tweeterclone=Tweeterclone.new(tweeterclone_params)
    render new_tweeterclone_path if @tweeterclone.invalid?
  end
  # GET /tweeterclones/new
  def new
    if params[:back]
      @tweeterclone = Tweeterclone.new(tweeterclone_params)
    else
      @tweeterclone = Tweeterclone.new
    end
  end

  # GET /tweeterclones/1/edit
  def edit
  end

  # POST /tweeterclones
  # POST /tweeterclones.json
  def create
    @tweeterclone = Tweeterclone.new(tweeterclone_params)

    respond_to do |format|
      if @tweeterclone.save
        format.html { redirect_to tweeterclones_path, notice: 'Tweeterclone was successfully created.' }
        format.json { render :show, status: :created, location: @tweeterclone }
      else
        format.html { render :new }
        format.json { render json: @tweeterclone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeterclones/1
  # PATCH/PUT /tweeterclones/1.json
  def update
    respond_to do |format|
      if @tweeterclone.update(tweeterclone_params)
        format.html { redirect_to tweeterclones_path, notice: 'Tweeterclone was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeterclone }
      else
        format.html { render :edit }
        format.json { render json: @tweeterclone.errors, status: :unprocessable_entity }
      end
    end
    
    # @tweeterclone=Tweeterclone.find(params[:id])
    # if @tweeterclone.update(tweeterclone_params)
    #   redirect_to tweeterclones_path, notice: "The Tweet updated successfully!"
    # else
    #   render 'edit'
    # end
  end

  # DELETE /tweeterclones/1
  # DELETE /tweeterclones/1.json
  def destroy
    @tweeterclone.destroy
    respond_to do |format|
      format.html { redirect_to tweeterclones_url, notice: 'Tweeterclone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeterclone
      @tweeterclone = Tweeterclone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweeterclone_params
      params.require(:tweeterclone).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeterclones_helper.rb
module TweeterclonesHelper
  def choose_new_or_edit
        if action_name == 'new' #|| action_name == 'confirm'
          confirm_tweeterclones_path
        elsif action_name == 'edit'
          tweeterclone_path
        end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterclone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #e6ecf0">
    
 <nav class="navbar navbar-toggleable-md navbar-expand-md navbar-light bg-light">
   <div class="container">
  <a class="navbar-brand" href="#"><span class="glyphicons glyphicons-home"></span>Twitterclone</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="material-icons icon" style="font-size:18px !important;">notifications</i><span class="text">Notifications</span></a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link" href="#"><i class="glyphicon glyphicon-envelope" style="color:#e6ecf0"></i> Messages</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <button type="button" class="btn btn-primary tweetButton" style="background-color:#4ab3f4;border: 1px solid #1da1f2;border-radius:100px
        " data-toggle="modal" data-target="#tweetModal">Tweet</button>
      </li>  
    </ul>
  </div>  
  </div>
</nav>
<div class="modal fade" id="tweetModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Compose new Tweet</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Tweet</button>
      </div>
    </div>
  </div>
</div>
<div class="row">
    <div class="col-1"></div>
    <div class="col-10"><%= yield%></div>
    <div class="col-1"></div>
</div>
<div class="container-fluid">
<footer class="text-white mt-4" style="position:fixed;background-color: #343a40;width: 100% ;height: 60px ;bottom: 0 ;text-align: center; padding: 19px ;">
  <label>CopyRigth©2018 Twitter</label>
</footer>
</div>
  </body>
</html>

app/views/tweeterclones/_form.html.erb
<%= form_with(model: @tweeterclone,local: true, url: choose_new_or_edit) do |f| %>
  <% if @tweeterclone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweeterclone.errors.count, "error") %> Please your tweet must be between 1 and 140 character(s)</h2>

      <ul>
      <% @tweeterclone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <br><br>
  <div class="field form-group row">
    <br>
    <%= f.label :content, class: 'col-sm-2 control-label', style:'font-size:40px' %>
    <div class="col-sm-10">
      <%= f.text_area :content, class: 'form-control' %>
    </div>
  </div>
  <%= link_to 'Back', tweeterclones_path , class: 'btn btn-success back', style:'margin-left:700px;width:200px' %>
   <%= f.submit 'Tweet', class: 'btn btn-primary', style:'width:200px'%>
 
<% end %>

app/views/tweeterclones/confirm.html.erb
<h3 style="margin-top:30px"><center> the following contents.</center>Tweet</h3>

<%= form_with(model: @tweeterclone, url: tweeterclones_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p style="margin-top:30px;font-size:20px">Content:<%= @tweeterclone.content %></p>
  <%= form.submit  "submit",class:'glyphicon glyphicon-save btn btn-success' ,style:'float:left;margin:20px;width:200px'%>
<% end %>

<%= form_with(model: @tweeterclone, url: new_tweeterclone_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit  "Back", name: 'back',class:'glyphicon glyphicon-arrow-left btn btn-primary',style:'margin:20px;width:200px' %>
  

<% end %>

app/views/tweeterclones/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form', tweeterclone: @tweeterclone %>

<!--<%= link_to 'Show', tweeterclones_path %> |-->
<!--<%= link_to 'Back', tweeterclones_path %>-->

app/views/tweeterclones/index.html.erb
<p id="notice"><%= notice %></p>
<!--<h1>Tweeterclones</h1>-->
<div class="row">
    <div class="col" style="height:280px;background-color:#fff;padding-left:0px !important;padding-right:0px !important">
      <div class="" style="height:130px;background-color:#1DA1F2"></div>
      <div>
       <div style="text-align:center !important"> <a href="#" >Kalisa Athanasie</a><br><span>@Kalisa</span></div><br>
        <label style="margin-left:50px">Tweeets</label><label style="margin-left:50px">Following</label><br>
        <label style="margin-left:70px"><%= @tweetercount%></label><label style="margin-left:90px">20</label>
      </div><br>
      <div>
        <%= link_to new_tweeterclone_path, class: 'btn btn-success',style:'width:100%' do %>
          <i class="glyphicon glyphicon-plus"></i> New Tweeterclone
      <% end %></div>
    </div>
    
    <div class="col-6">
            <% @tweeterclones.each do |tweeterclone| %>
             <div style="background-color:#fff;padding-left:0px !important;padding-right:0px !important">
                <label style="padding:10px 0px 10px 100px">Tweeted on <%= tweeterclone.created_at%></label> <br>
                <label style="padding:10px 0px 0px 30px"><%= tweeterclone.content%></label> <br>
                <label  style="padding-left:50%"><span style="color:#007bff" class='glyphicon glyphicon-eye-open'></span><%= link_to  'Show', tweeterclone %></label>
                <label style="padding-left:20px"><span style="color:#007bff" class="glyphicon glyphicon-pencil"></span><%= link_to 'Edit', edit_tweeterclone_path(tweeterclone) %></label>
                <label style="padding-bottom:30px;padding-left:20px"><span style="color:#007bff" class="glyphicon glyphicon-trash"></span><%= link_to 'Destroy', tweeterclone, method: :delete, data: { confirm: 'Are you sure?' } %></label>
              </div>
              <br>
            <% end %>
            <div class="container pagination justify-content-center" >
              <%= paginate @tweeterclones, theme: 'twitter-bootstrap-4'%>
            </div>
    </div>
    <div class="col">
      <div class="col" style="width: 280px;height:270px;background-color:#fff;margin-bottom:20px;padding:30px !important">
        <label>Who to follow</label>
        <a href="#" style="font-size:14px;">Reflesh</a>
        <a href="#" style="font-size:14px;">View All</a>
      </div>
      <div class="col" style="width: 280px;height:200px;background-color:#fff;padding:10px !important">
        <label style="font-size:14px;color: #657786;">© 2018 Twitter</label>
        <a href="#" style="font-size:14px;color: #657786;">About</a>
        <a href="#" style="font-size:14px;color: #657786;">Help Center</a>
        <a href="#" style="font-size:14px;color: #657786;">Terms</a><br>
        <a href="#" style="font-size:14px;color: #657786;">Privacy policy</a>
        <a href="#" style="font-size:14px;color: #657786;">Cookies</a>
        <a href="#" style="font-size:14px;color: #657786;">Ads info</a>
        <a href="#" style="font-size:14px;color: #657786;">Brand</a>
        <a href="#" style="font-size:14px;color: #657786;">Blog</a><br>
        <a href="#" style="font-size:14px;color: #657786;"> Status</a>
        <a href="#" style="font-size:14px;color: #657786;">Apps</a>
        <a href="#" style="font-size:14px;color: #657786;">Jobs</a>
        <a href="#" style="font-size:14px;color: #657786;"> Marketing</a>
        <a href="#" style="font-size:14px;color: #657786;"> <a href="#" style="font-size:14px;color: #657786;">Businesses</a><br>
        <a href="#" style="font-size:14px;color: #657786;">Developers</a><hr>
        <a href="#" style="font-size:14px;color: #657786;margin-left:50px">Advertise with Twitter</a
      </div>
    </div>
  </div>



<br>

app/views/tweeterclones/new.html.erb
<h1 style="text-align:center">Compose new Tweet</h1>

<%= render 'form', tweeterclone: @tweeterclone %>

app/views/tweeterclones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @tweeterclone.content %>
</p>

<%= link_to 'Edit', edit_tweeterclone_path(@tweeterclone) %> |
<%= link_to 'Back', tweeterclones_path %>